/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2023-01-11 08:44:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/lhy/pro07/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668994785251L));
    _jspx_dependants.put("jar:file:/D:/lhy/pro07/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/lhy/pro07/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<footer>\r\n");
      out.write("	<div class=\"nav container\">\r\n");
      out.write("		<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/images/f_logo.png\">\r\n");
      out.write("		<div class=\"col-12 col-lg-auto me-lg-auto mt-2 pl-3\">\r\n");
      out.write("			<span>누리집 이용안내</span>\r\n");
      out.write("			<span>개인정보처리방침</span>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"text-end form-select-sm\">\r\n");
      out.write("			<select aria-label=\"Default select example\" onchange=\"sel_link(this)\">\r\n");
      out.write("				<option selected style=\"display:none;\">산하기관 바로가기</option>\r\n");
      out.write("			  	<option value=\"https://www.koica.go.kr/sites/koica_kr/index.do\">한국국제협력단</option>\r\n");
      out.write("				<option value=\"http://www.kf.or.kr/\">한국국제교류재단</option>\r\n");
      out.write("				<option value=\"http://www.okf.or.kr/\">재외동포재단</option>\r\n");
      out.write("				<option value=\"http://k-af.or.kr/\">한·아프리카재단</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			<select aria-label=\"Default select example\" onchange=\"sel_link(this)\">\r\n");
      out.write("				<option selected style=\"display:none;\">정부기관 바로가기</option>\r\n");
      out.write("				<option value=\"http://www.korea.go.kr/\">대한민국 정부포털</option>\r\n");
      out.write("				<option value=\"http://www.president.go.kr\">대통령실</option>\r\n");
      out.write("				<option value=\"http://www.humanrights.go.kr\">국가인권위원회</option>\r\n");
      out.write("				<option value=\"http://www.nis.go.kr\">국가정보원</option>\r\n");
      out.write("				<option value=\"http://www.bai.go.kr\">감사원</option>\r\n");
      out.write("				<option value=\"http://www.kcc.go.kr\">방송통신위원회</option>\r\n");
      out.write("				<option value=\"http://www.opm.go.kr\">국무총리실</option>\r\n");
      out.write("				<option value=\"http://www.mpm.go.kr\">인사혁신처</option>\r\n");
      out.write("				<option value=\"http://www.moleg.go.kr\">법제처</option>\r\n");
      out.write("				<option value=\"http://www.mpva.go.kr\">국가보훈처</option>\r\n");
      out.write("				<option value=\"http://www.mfds.go.kr\">식품의약품안전처</option>\r\n");
      out.write("				<option value=\"http://http://www.ftc.go.kr\">공정거래위원회</option>\r\n");
      out.write("				<option value=\"http://www.fsc.go.kr\">금융위원회</option>\r\n");
      out.write("				<option value=\"http://www.acrc.go.kr\">국민권익위원회</option>\r\n");
      out.write("				<option value=\"http://www.nssc.go.kr\">원자력안전위원회</option>\r\n");
      out.write("				<option value=\"http://www.mosf.go.kr\">기획재정부</option>\r\n");
      out.write("				<option value=\"http:http://www.nts.go.kr\">- 국세청</option>\r\n");
      out.write("				<option value=\"http://www.customs.go.kr\">- 관세청</option>\r\n");
      out.write("				<option value=\"http://www.pps.go.kr\">- 조달청</option>\r\n");
      out.write("				<option value=\"http://www.kostat.go.kr\">- 통계청</option>\r\n");
      out.write("				<option value=\"http://www.msit.go.kr\">과학기술정보통신부</option>\r\n");
      out.write("				<option value=\"http://www.moe.go.kr\">교육부</option>\r\n");
      out.write("				<option value=\"http://www.mofa.go.kr\">외교부</option>\r\n");
      out.write("				<option value=\"http://www.unikorea.go.kr\">통일부</option>\r\n");
      out.write("				<option value=\"http://www.moj.go.kr\">법무부</option>\r\n");
      out.write("				<option value=\"http://www.spo.go.kr\">- 검찰청</option>\r\n");
      out.write("				<option value=\"http://www.mnd.go.kr\">국방부</option>\r\n");
      out.write("				<option value=\"http://www.mma.go.kr\">- 병무청</option>\r\n");
      out.write("				<option value=\"http://www.mnd.go.kr\">국방부</option>\r\n");
      out.write("				<option value=\"http://www.dapa.go.kr\">- 방위사업청</option>\r\n");
      out.write("				<option value=\"http://www.mois.go.kr\">행정안전부</option>\r\n");
      out.write("				<option value=\"http://www.police.go.kr\">- 경찰청</option>\r\n");
      out.write("				<option value=\"http://www.nfa.go.kr\">- 소방청</option>\r\n");
      out.write("				<option value=\"http://www.mcst.go.kr\">문화체육관광부</option>\r\n");
      out.write("				<option value=\"http://www.cha.go.kr\">- 문화재청</option>\r\n");
      out.write("				<option value=\"http://www.mafra.go.kr\">농림축산식품부</option>\r\n");
      out.write("				<option value=\"http://www.rda.go.kr\">- 농촌진흥청</option>\r\n");
      out.write("				<option value=\"http://www.forest.go.kr\">- 산림청</option>\r\n");
      out.write("				<option value=\"http://www.motie.go.kr\">산업통상자원부</option>\r\n");
      out.write("				<option value=\"http://www.kipo.go.kr\">- 특허청</option>\r\n");
      out.write("				<option value=\"http://www.mohw.go.kr\">보건복지부</option>\r\n");
      out.write("				<option value=\"http://www.me.go.kr\">환경부</option>\r\n");
      out.write("				<option value=\"http://www.kma.go.kr\">- 기상청</option>\r\n");
      out.write("				<option value=\"http://www.moel.go.kr\">고용노동부</option>\r\n");
      out.write("				<option value=\"http://www.mogef.go.kr\">여성가족부</option>\r\n");
      out.write("				<option value=\"http://www.molit.go.kr\">국토교통부</option>\r\n");
      out.write("				<option value=\"http://www.saemangeum.go.kr\">- 새만금개발청</option>\r\n");
      out.write("				<option value=\"http://www.naacc.go.kr\">- 행정중심복합도시건설청</option>\r\n");
      out.write("				<option value=\"http://www.mof.go.kr\">해양수산부</option>\r\n");
      out.write("				<option value=\"http://www.kcg.go.kr\">- 해양경찰청</option>\r\n");
      out.write("				<option value=\"http://www.smba.go.kr\">중소벤처기업부</option>\r\n");
      out.write("			</select>\r\n");
      out.write("		</div>\r\n");
      out.write("		<script>\r\n");
      out.write("		function sel_link(sel) {\r\n");
      out.write("		   location.href = sel.value;\r\n");
      out.write("		}\r\n");
      out.write("		</script>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"footer container\">\r\n");
      out.write("		<div class=\"copyright\">\r\n");
      out.write("			<p>주소 : 03172 서울특별시 종로구 사직로8길 60 |(여권영사민원실) 서울특별시 서초구 남부순환로 2558 외교타운 6층</p>\r\n");
      out.write("			<p>전화번호 : 02.2100.2114(주간), 02.3210.0404(영사콜센터, 24시간)</p>\r\n");
      out.write("			<p>팩스 : 02.2100.7998</p>\r\n");
      out.write("			<p>본 누리집의 모든 권리는 외교부에 귀속됩니다.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("		<div class=\"server\">\r\n");
      out.write("			<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serverTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/common/footer.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path1");
      // /WEB-INF/views/common/footer.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/common/footer.jsp(6,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
